### PR TITLE
[WIP] - Added ability to cancel vertical or horizontal alignment

### PR DESCRIPTION
**Pull request by liiight**
With regard to https://github.com/Flexget/Flexget/issues/1584, our usage of PorcelainTable requires the ability to disable all table alignments. 

To Do:
- [ ] Update tests.

### CODE REVIEW

**Comment by Robpol86** [comment]
Can you provide a repr() of the output before and after your change? I'm not sure I 100% understand. Does your change change this:
```pycon
>>> for line in PorcelainTable(table_data).table.splitlines(): repr(line)
... 
"' Heading1     | Heading2     '"
"' row1 column1 | row1 column2 '"
"' row2 column1 | row2 column2 '"
"' row3 column1 | row3 column2 '"
```

to this:
```pycon
>>> for line in PorcelainTable(table_data).table.splitlines(): repr(line)
... 
"'Heading1     | Heading2'"
"'row1 column1 | row1 column2'"
"'row2 column1 | row2 column2'"
"'row3 column1 | row3 column2'"
```

**Comment by liiight** [comment]
Base:
```
 Platform | Years     | Notes                    
 Mk5      | 2007-2009 | The Golf Mk5 Variant was 
          |           | introduced in 2007.      
 MKVI     | 2009-2013 | Might actually be Mk5. 
```
```python
table.horizontal_align = False
```
```
Platform|Years|Notes
Mk5|2007-2009|The Golf Mk5 Variant was
||introduced in 2007.
MKVI|2009-2013|Might actually be Mk5.
```
```python
table.vertical_align = False
```
```
Platform|Years|Notes
Mk5|2007-2009|The Golf Mk5 Variant was\nintroduced in 2007.
MKVI|2009-2013|Might actually be Mk5.
```

**Comment by Robpol86** [comment]
I'm not sure if this would really be in scope of terminaltables. It's not really a table anymore, more like pipe delimited lines. What benefit would terminaltables provide over just `['|'.join(row) for row in table_data]`?

**Comment by liiight** [comment]
I understand this maybe too much of a private case and would understand if you reject this. For me, it's way more elegant to let terminaltable handle it by setting two flags than to have another code path.

**Comment by Robpol86** [comment]
Yea I think this would be too specific for terminaltables :( thanks for the pull request anyway, always glad to review this kind of stuff!

**Comment by liiight** [comment]
No problem. While we're at it, how you feel about a csv table?

**Comment by Robpol86** [comment]
To have it output something like:
```
Platform,Years,Notes
Mk5,2007-2009,The Golf Mk5 Variant was\nintroduced in 2007.
MKVI,2009-2013,Might actually be Mk5.
```
?

If so I think it too is out of scope. termintaltables is more for horizontal text alignment. If it's not padding cells it's basically just joining cells with a lot of function call overhead.

**Comment by liiight** [comment]
Yeah, guess you're right. Thanks for considering anyway.

**Pull request closed without merging**
